json.id student.id
json.first_name student.first_name
json.last_name student.last_name
json.email student.email
json.phone_number student.phone_number
json.short_bio student.short_bio
json.linkedin student.linkedin
json.twitter student.twitter
json.blog_site student.blog_site
json.resume student.resume
json.github student.github
json.photo student.photo
json.experiences student.experiences
json.educations student.educations
json.capstones student.capstones
